---
build_from:
  amd64: ghcr.io/hassio-addons/debian-base/amd64:7.3.3
  armhf: ghcr.io/hassio-addons/debian-base/armhf:7.3.3
  armv7: ghcr.io/hassio-addons/debian-base/armv7:7.3.3
  aarch64: ghcr.io/hassio-addons/debian-base/aarch64:7.3.3
codenotary:
  base_image: codenotary@frenck.dev
  signer: codenotary@degatano.com
