---
build_from:
  amd64: ghcr.io/hassio-addons/debian-base/amd64:7.0.0
  armhf: ghcr.io/hassio-addons/debian-base/armhf:7.0.0
  armv7: ghcr.io/hassio-addons/debian-base/armv7:7.0.0
  aarch64: ghcr.io/hassio-addons/debian-base/aarch64:7.0.0
codenotary:
  base_image: codenotary@frenck.dev
  signer: codenotary@degatano.com
