---
build_from:
  amd64: ghcr.io/hassio-addons/debian-base/amd64:stable
  armhf: ghcr.io/hassio-addons/debian-base/armhf:stable
  armv7: ghcr.io/hassio-addons/debian-base/armv7:stable
  aarch64: ghcr.io/hassio-addons/debian-base/aarch64:stable
codenotary:
  base_image: codenotary@frenck.dev
  signer: codenotary@degatano.com
