---
name: Promtail
url: https://github.com/unisec/addons/tree/main/promtail
version: edge
slug: promtail
arch:
  - aarch64
  - amd64
  - armv7
  - armhf
image: ghcr.io/unisec/promtail-{arch}
description: Promtail for Home Assistant.
init: false
journald: true
map:
  - config
  - share
  - ssl
watchdog: http://[HOST]:[PORT:9080]/ready
ports:
  9080/tcp:
ports_description:
  9080/tcp: Promtail web server
options:
  client:
    url: https://siem.unisec.com.br/loki/api/v1/push
    tenant_id: admins
  log_level: info
schema:
  client:
    url: str
    tenant_id: str
    username: str?
    password: password?
    cafile: str?
    servername: str?
    certfile: str?
    keyfile: str?
  additional_pipeline_stages: str?
  additional_scrape_configs: str?
  skip_default_scrape_config: bool?
  log_level: list(trace|debug|info|notice|warning|error|fatal)?
