---
name: "Build add-on"


on: 
  push:
    branches:
      - main
      - develop

jobs:
  build:
    name: Job Test Build ${{ matrix.arch }} ${{ matrix.addon }} add-on
    runs-on: ubuntu-latest
    strategy:

      matrix:
        addon: [ "platformio", "ssh" , "wireguard" ]
        arch:  [ "aarch64", "amd64", "armhf", "armv7", "i386"]

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        
      - name: Test build
        uses: home-assistant/builder@master
        with:
          args: |
            --${{ matrix.arch }} \
            --target /data/${{ matrix.addon }} \
            --docker-hub unicontrol \
            --image ${{ matrix.addon }}-${{ matrix.arch }} \
            --addon \
            --test 