---
name: "Desenvolvimento - Construção add-on "
 
on:
  pull_request:
    branches: ["main"]

  push:
    branches: ["develop"]

jobs:
  build:
    name: Trabalho Teste - Construindo Add-on ${{ matrix.addon }} na arquitetura ${{ matrix.arch }}
    runs-on: ubuntu-latest
    outputs:
      changed_files: ${{ steps.changed_files.outputs.all }}
      changed_addons: ${{ steps.changed_addons.outputs.addons }}
      changed: ${{ steps.changed_addons.outputs.changed }}

    strategy:
      matrix:
        addon: [ "platformio", "ssh" , "wireguard","amazon-s3-backup","promtail"]
        arch:  [ "aarch64", "amd64", "armhf", "armv7"]

    steps:
      - uses: actions/checkout@v3

      - name: Get changed files
        id: changed_files
        uses: jitterbit/get-changed-files@v1

      - name: Get add-ons
        id: addons
        run: |
          declare -a addons
          for addon in $(find ./ -name config.json -o -name config.yaml | cut -d "/" -f2 | sort -u); do
            addons+=("$addon");
          done
          echo "addons=${addons[@]}" >> "$GITHUB_OUTPUT"

      - name: Get changed add-ons
        id: changed_addons
        run: |
          declare -a changed_addons
          for addon in ${{ steps.addons.outputs.addons }}; do
            if [[ "${{ steps.changed_files.outputs.all }}" =~ $addon ]]; then
              for file in ${{ env.MONITORED_FILES }}; do
                  if [[ "${{ steps.changed_files.outputs.all }}" =~ $addon/$file ]]; then
                    if [[ ! "${changed_addons[@]}" =~ $addon ]]; then
                      changed_addons+=("\"${addon}\",");
                    fi
                  fi
              done
            fi
          done

          changed=$(echo ${changed_addons[@]} | rev | cut -c 2- | rev)
          if [[ -n ${changed} ]]; then
            echo "Changed add-ons: $changed";
            echo "changed=true" >> "$GITHUB_OUTPUT";
            echo "addons=[$changed]" >> "$GITHUB_OUTPUT";
          else
            echo "No add-on had any monitored files changed (${{ env.MONITORED_FILES }})";
          fi


      - name: Login no DockerHub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

#      - name: Construindo ${{ matrix.addon }} 
#        uses: home-assistant/builder@master
#        with:
#          args: |
#            --${{ matrix.arch }} \
#            --target /data/${{ matrix.addon }} \
#            --docker-hub ghcr.io/unisec \
#            --image ${{ matrix.addon }}-${{ matrix.arch }} \
#            --addon \
#            --test