---
name: "Desenvolvimento - Construção add-on "
 
on:
  pull_request:
    branches: ["main"]

  push:
    branches: ["develop"]

jobs:
  build:
    name: Trabalho Teste - Construindo Add-on ${{ matrix.addon }} na arquitetura ${{ matrix.arch }}
    runs-on: ubuntu-latest
    outputs:
      changed_files: ${{ steps.changed_files.outputs.all }}
      changed_addons: ${{ steps.changed_addons.outputs.addons }}
      changed: ${{ steps.changed_addons.outputs.changed }}

    strategy:
      matrix:
        #addon: [ "platformio", "ssh" , "wireguard","amazon-s3-backup","promtail"]
        addon: ${{ fromJson(steps.addons.outputs.addons) }}
        arch:  [ "aarch64", "amd64", "armhf", "armv7"]
    steps:
      - uses: actions/checkout@v3

      - name: Get changed files
        id: changed_files
        uses: jitterbit/get-changed-files@v1

      - name: Get add-ons
        id: addons
        run: |
          declare -a changed_addons
          for changed_addon in $(find ./ -name config.json -o -name config.yaml | cut -d "/" -f2 | sort -u); do
            changed_addons+=("\"${changed_addon}\",");
          done
          changed=$(echo ${changed_addons[@]} | rev | cut -c 2- | rev)
          echo "addons=[$changed]" >> "$GITHUB_OUTPUT"

      - name: Login no DockerHub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Construindo ${{ matrix.addon }} 
        uses: home-assistant/builder@master
        with:
          args: |
            --${{ matrix.arch }} \
            --target /data/${{ matrix.addon }} \
            --docker-hub ghcr.io/unisec \
            --image ${{ matrix.addon }}-${{ matrix.arch }} \
            --addon \
            --test