---
name: "Construção add-on"
 
on:
  push:
    branches: ["main"]

jobs:
  build:
    name: Construindo Add-on ${{ matrix.addon }} na arquitetura ${{ matrix.arch }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        addon: [ "platformio", "ssh" , "wireguard" ]
        arch:  [ "aarch64", "amd64", "armhf", "armv7", "i386"]

    steps:
      - uses: actions/checkout@v3

      - name: Login no DockerHub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Construindo add-on ${{ matrix.addon }} 
        uses: home-assistant/builder@master
        with:
          args: |
            --${{ matrix.arch }} \
            --target /data/${{ matrix.addon }} \
            --docker-hub ghcr.io/unisec \
            --image ${{ matrix.addon }}-${{ matrix.arch }} \
            --addon 